M48
; DRILL file {KiCad (6.0.7)} date Wed Sep 14 15:07:52 2022
; FORMAT={-:-/ absolute / metric / decimal}
; #@! TF.CreationDate,2022-09-14T15:07:52+02:00
; #@! TF.GenerationSoftware,Kicad,Pcbnew,(6.0.7)
; #@! TF.FileFunction,NonPlated,1,4,NPTH
FMAT,2
METRIC
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T1C0.650
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T2C1.750
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T3C2.200
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T4C4.000
%
G90
G05
T1
X156.61Y-64.6
X162.39Y-64.6
T2
X144.62Y-90.9
X154.78Y-90.9
X163.67Y-90.9
X173.83Y-90.9
T3
X138.0Y-60.05
X138.0Y-102.225
X181.5Y-60.05
X181.5Y-102.225
T4
X149.7Y-90.9
X168.75Y-90.9
T0
M30
